### PR TITLE
[KED-2960] Remove notice from PR template

### PR DESCRIPTION
**Pull request by MerelTheisenQB**
## Notice

- [X] I acknowledge and agree that, by checking this box and clicking "Submit Pull Request":

- I submit this contribution under the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt) and represent that I am entitled to do so on behalf of myself, my employer, or relevant third parties, as applicable.
- I certify that (a) this contribution is my original creation and / or (b) to the extent it is not my original creation, I am authorised to submit this contribution on behalf of the original creator(s) or their licensees.
- I certify that the use of this contribution as authorised by the Apache 2.0 license does not violate the intellectual property rights of anyone else.

## Motivation and Context
As part of our move to the Linux Foundation we need to enable a GitHub DCO plugin for contributors, which will take care of what's now agreed to in the "Notice".

## How has this been tested?
-

## Checklist

- [ ] Opened this PR as a 'Draft Pull Request' if it is work-in-progress
- [X] Assigned myself to the PR
- [ ] Added tests to cover my changes
- [ ] Added new entries to the `RELEASE.md` file

### CODE REVIEW

**Review by lorenabalan — COMMENTED** [review]
Looking at the diff... is `develop` behind `master`? 😅

**Comment by MerelTheisenQB** [comment]
> Looking at the diff... is `develop` behind `master`? 😅

😮 Let me see what's going on.

**Comment by MerelTheisenQB** [comment]
Hmm yeah it looks like we never did a `master back to develop` merge after version `0.4.1` was released.. It should be fixed by just making a PR to merge master into develop right? 

Ohhhh I see we merged two PRs directly to master: https://github.com/quantumblacklabs/kedro-airflow/pull/81 and https://github.com/quantumblacklabs/kedro-airflow/pull/80 😬

**Comment by lorenabalan** [comment]
Erm okay maybe now's the time to delete `develop` and just merge everything to `master` or `main`. 😂  It's what we do on `kedro-telemetry` already, and I think our Release checklist should cover that.

**Comment by lorenabalan** [comment]
Sorry for the confusion!

**Review by lorenabalan — APPROVED** [review]

**Pull request merged**
